services:
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: dosage_drugs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: dosage_drugs
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: dosage_drugs_minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # Порт для API (сюда будут стучаться картинки)
      - "9001:9001"  # Порт для веб-консоли управления
    environment:
      MINIO_ROOT_USER: minioadmin      # Логин для входа
      MINIO_ROOT_PASSWORD: minioadmin  # Пароль для входа
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
